# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jbspeakr.cc
email: jan@brennenstuhl.me
description: >
  Jan Brennenstuhl about application security, identity management & authorization concepts. With opinions about OAuth, JWT and clean code web development.
logo: "/assets/images/jbspeakr-logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jbspeakr.cc" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Jan Brennenstuhl'
bio: >
  Jan is a full-stack web developer, computer security enthusiast &amp; clean code artist.
  He lives in Berlin, is currently working for Zalando SE and loves urban art, coffee &amp; cycling.
author_image: "/assets/images/jan-brennenstuhl.jpg"
twitter_username: jbspeakr
github_username:  jbspeakr

# Google Analytics
analytics_id: "UA-36462674-4"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

jekyll-minifier:
  exclude:
    - 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
    - '.htaccess'

gems:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-paginate
